import { HttpStatus } from '@nestjs/common';

export enum ErrorCode {
  INVALID_CODE,
  UNCATEGORIZED_CODE,
  INVALID_USERNAME,
  NULL_USERNAME,
  NULL_PASSWORD,
  INVALID_PASSWORD,
  UNAUTHENTICATED,
  UNAUTHORIZED,
  NOT_FOUND,
  SERVER_ERROR,
  INVALID_DECKNAME,
  MISSING_SECRET_KEY,
  EMAIL_EXISTS,
  VERIFY_TIME_OUT,
  INVALID_OTP,
  WATTING_TIME_OTP,
  ACCOUNT_NOT_VERIFIED,
  EMAIL_EXISTS_NOT_VERIFY,
  CURRENT_PASSWORD_NOT_MATCH,
  INVALID_TOKEN_GOOGLE,
  ACCOUNT_IS_LOGOUT,
  MISSING_ACCESS_TOKEN,
  NAME_TOO_SHORT,
  NAME_CONTAINS_NUMBERS,
  NAME_CONTAINS_SPECIAL_CHARS,
  NAME_TOO_LONG,
  NAME_IS_BLANK,
  AVATAR_INVALID_FILE_TYPE,
  AVATAR_NO_FILE_SELECTED,
  PASSWORD_SAME_AS_OLD,
  NEW_PASSWORD_EMPTY,
  OLD_PASSWORD_EMPTY,
  OLD_PASSWORD_INCORRECT,
  PASSWORD_FORMAT_INVALID,
  USER_NOT_FOUND,
  USER_ALREADY_SUSPENDED,
  USER_ALREADY_ACTIVE,
  ADMIN_REQUIRED,
  USER_IS_BANNED,
  USER_ALREADY_HAS_ROLE,
  INVALID_REQUEST,
  MEMBERSHIP_PACKAGE_EXISTS,
  MEMBERSHIP_PACKAGE_NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  USER_ALREADY_DELETED,
}
export const ErrorDetails = {
  [ErrorCode.INVALID_CODE]: {
    code: 1000,
    message: 'Invalid code',
    httpStatus: HttpStatus.INTERNAL_SERVER_ERROR,
  },
  [ErrorCode.UNCATEGORIZED_CODE]: {
    code: 9999,
    message: 'Uncategorized error',
    httpStatus: HttpStatus.INTERNAL_SERVER_ERROR,
  },
  [ErrorCode.INVALID_USERNAME]: {
    code: 1001,
    message: 'Username must be between 6 - 25 characters',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.NULL_USERNAME]: {
    code: 1002,
    message: 'Username must not be null',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.NULL_PASSWORD]: {
    code: 1003,
    message: 'Password must not be null',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.INVALID_PASSWORD]: {
    code: 1004,
    message:
      'Password must have at least 8 characters with uppercase, lowercase, number, and special character',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.UNAUTHENTICATED]: {
    code: 1005,
    message: 'Unauthenticated',
    httpStatus: HttpStatus.UNAUTHORIZED,
  },
  [ErrorCode.UNAUTHORIZED]: {
    code: 1006,
    message: 'You do not have permission',
    httpStatus: HttpStatus.FORBIDDEN,
  },
  [ErrorCode.NOT_FOUND]: {
    code: 1007,
    message: 'Resource not found',
    httpStatus: HttpStatus.NOT_FOUND,
  },
  [ErrorCode.SERVER_ERROR]: {
    code: 1008,
    message: 'Internal server error',
    httpStatus: HttpStatus.INTERNAL_SERVER_ERROR,
  },
  [ErrorCode.INVALID_DECKNAME]: {
    code: 1009,
    message: 'Invalid DeckName',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.MISSING_SECRET_KEY]: {
    code: 1010,
    message: 'Missing JWT_SECRET in environment variables',
    httpStatus: HttpStatus.INTERNAL_SERVER_ERROR,
  },
  [ErrorCode.EMAIL_EXISTS]: {
    code: 1011,
    message: 'Email exists & verified',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.VERIFY_TIME_OUT]: {
    code: 1012,
    message: 'Email verify is time out',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.INVALID_OTP]: {
    code: 1013,
    message: 'Invalid OTP',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.WATTING_TIME_OTP]: {
    code: 1014,
    message: 'Watting for next send OTP',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.ACCOUNT_NOT_VERIFIED]: {
    code: 1015,
    message: 'Account is unverify',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.EMAIL_EXISTS_NOT_VERIFY]: {
    code: 1016,
    message: 'Email is exits but not verify',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.CURRENT_PASSWORD_NOT_MATCH]: {
    code: 1017,
    message: 'Current password not match',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.INVALID_TOKEN_GOOGLE]: {
    code: 1018,
    message: 'Invalid token google',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.ACCOUNT_IS_LOGOUT]: {
    code: 1019,
    message: 'Account is log out',
    httpStatus: HttpStatus.UNAUTHORIZED,
  },
  [ErrorCode.MISSING_ACCESS_TOKEN]: {
    code: 1020,
    message: 'Missing access token',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.NAME_TOO_SHORT]: {
    code: 1021,
    message: 'Name must be 2 words',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.NAME_CONTAINS_NUMBERS]: {
    code: 1022,
    message: 'Name cannot contain numbers',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.NAME_CONTAINS_SPECIAL_CHARS]: {
    code: 1023,
    message: 'Name cannot contain special characters',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.NAME_TOO_LONG]: {
    code: 1024,
    message: 'Name is too long',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.NAME_IS_BLANK]: {
    code: 1025,
    message: 'Name cannot be blank',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.AVATAR_INVALID_FILE_TYPE]: {
    code: 1026,
    message: 'File format is incorrect',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.AVATAR_NO_FILE_SELECTED]: {
    code: 1027,
    message: 'Please select a photo to update',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.PASSWORD_SAME_AS_OLD]: {
    code: 1030,
    message: 'The new password cannot be the same as the old one',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.NEW_PASSWORD_EMPTY]: {
    code: 1031,
    message: 'Please enter a new password',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.OLD_PASSWORD_EMPTY]: {
    code: 1032,
    message: 'Please enter your current password',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.OLD_PASSWORD_INCORRECT]: {
    code: 1033,
    message: 'The current password is incorrect',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.PASSWORD_FORMAT_INVALID]: {
    code: 1034,
    message: 'The password format is invalid',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.USER_NOT_FOUND]: {
    code: 1035,
    message: 'User not found',
    httpStatus: HttpStatus.NOT_FOUND,
  },
  [ErrorCode.USER_ALREADY_SUSPENDED]: {
    code: 1036,
    message: 'User is already suspended',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.USER_ALREADY_ACTIVE]: {
    code: 1037,
    message: 'User is already active',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.ADMIN_REQUIRED]: {
    code: 1038,
    message: 'Admin permission required',
    httpStatus: HttpStatus.FORBIDDEN,
  },
  [ErrorCode.USER_IS_BANNED]: {
    code: 1040,
    message: 'User is banned',
    httpStatus: HttpStatus.FORBIDDEN,
  },
  [ErrorCode.USER_ALREADY_HAS_ROLE]: {
    code: 1041,
    message: 'User already has this role',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.INVALID_REQUEST]: {
    code: 1042,
    message: 'Invalid request',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.MEMBERSHIP_PACKAGE_EXISTS]: {
    code: 1043,
    message: 'Membership package with this level already exists',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
  [ErrorCode.MEMBERSHIP_PACKAGE_NOT_FOUND]: {
    code: 1044,
    message: 'Membership package not found',
    httpStatus: HttpStatus.NOT_FOUND,
  },
  [ErrorCode.INTERNAL_SERVER_ERROR]: {
    code: 1045,
    message: 'Internal server error',
    httpStatus: HttpStatus.INTERNAL_SERVER_ERROR,
  },
  [ErrorCode.USER_ALREADY_DELETED]: {
    code: 1046,
    message: 'User account already deleted',
    httpStatus: HttpStatus.BAD_REQUEST,
  },
};
